name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11.9 and Install Dependencies
      run: |
        python -m venv venv
        .\venv\Scripts\activate
        .\venv\Scripts\python -m pip install --upgrade pip
        .\venv\Scripts\pip install pyinstaller
        .\venv\Scripts\pip install pywebview
        .\venv\Scripts\pyinstaller --onefile --hidden-import=webview --hidden-import=webview.platforms.win --noconsole app.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-exe
        path: dist/app.exe
