name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11.9 and Install Dependencies
      run: |
        python -m venv venv
        .\venv\Scripts\activate  # Aktivasi virtual environment di PowerShell Windows
        pip install --upgrade pip
        pip install pyinstaller
        pip install webview
        pyinstaller --onefile --hidden-import=webview --hidden-import=webview.platforms.win --noconsole app.py
        cp -r $env:USERPROFILE\.pyenv\versions\3.11.9\lib\site-packages\webview\browser\static dist\  # Menggunakan $env:USERPROFILE untuk path home di PowerShell Windows

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-exe
        path: dist/app.exe
