name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.9  # Ganti dengan versi Python yang Anda gunakan

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pywebview
    - name: Build executable
      run: |
        pyinstaller --onefile --icon=icon.ico --hidden-import=webview --noconsole --name Kasir app.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-exe
        path: dist/Kasir.exe  # Sesuaikan dengan lokasi file executable yang dihasilkan
