name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11.9 and Install Dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install pyinstaller
        pip install webview
        pyinstaller --onefile --hidden-import=webview --hidden-import=webview.platforms.win --noconsole app.py
        cp -r ~/.pyenv/versions/3.11.9/lib/python3.11/site-packages/webview/browser/static dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-exe
        path: dist/app.exe
